import{a as L,S as w,i as l}from"./assets/vendor-BjRz3xa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const r of a.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const S="49733939-659891c25e41a9f00718666a7",b="https://pixabay.com/api/",q=async(e,s=1,o=15)=>{const n={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:o};return(await L.get(b,{params:n})).data},v=new w(".gallery a"),m=e=>{const s=document.querySelector(".gallery"),o=document.createElement("div");o.classList.add("gallery-temp");const n=e.map(r=>`<li>
          <a href="${r.largeImageURL}">
            <img src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <div class="info">
            <p><span>Likes</span><br> ${r.likes}</p>
            <p><span>Views</span><br> ${r.views}</p>
            <p><span>Comments</span><br> ${r.comments}</p>
            <p><span>Downloads</span><br> ${r.downloads}</p>
          </div>
        </li>`).join("");o.innerHTML=n;const t=o.querySelectorAll("img"),a=Array.from(t).map(r=>new Promise((g,f)=>{r.onload=g,r.onerror=f}));Promise.all(a).then(()=>{s.insertAdjacentHTML("beforeend",n),v.refresh(),d(),u(),M()}).catch(r=>{console.error("Image loading failed:",r),d(),u()})},P=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},A=()=>{document.querySelector(".search-loader").classList.add("show")},d=()=>{document.querySelector(".search-loader").classList.remove("show")},B=()=>{document.querySelector(".load-more-loader").classList.add("show")},u=()=>{document.querySelector(".load-more-loader").classList.remove("show")},M=()=>{document.querySelector(".load-more").classList.remove("hidden")},i=()=>{document.querySelector(".load-more").classList.add("hidden")},p=document.querySelector(".form"),E=p.querySelector("input[name='search-text']"),F=document.querySelector(".load-more");let c=1,h="";const y=async(e,s)=>{try{const o=await q(e,s);if(!o||!Array.isArray(o.hits))throw new Error("Invalid API response structure");return o}catch{return l.error({title:"",message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB"}),{hits:[],totalHits:0}}};p.addEventListener("submit",async e=>{e.preventDefault();const s=E.value.trim();if(!s){l.warning({title:"Oops!",message:"Please enter a search term!"});return}h=s,c=1,P(),i(),A();const o=await y(s,c);o.hits.length>0?m(o.hits):(i(),l.warning({title:"",message:"Sorry, there are no images matching your search query. Please try again!"}))});F.addEventListener("click",async()=>{c+=1,B();const e=await y(h,c);e.hits.length>0&&(m(e.hits),I());const s=e.totalHits;c*15>=s&&(i(),l.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#4E75FF",messageColor:"#FAFAFB"}))});const I=()=>{const e=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
