import{a as w,S,i as c}from"./assets/vendor-BjRz3xa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const r of a.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const P="49733939-659891c25e41a9f00718666a7",b="https://pixabay.com/api/",q=async(e,s=1,o=15)=>{const n={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:o};return(await w.get(b,{params:n})).data},v=new S(".gallery a"),h=e=>{const s=document.querySelector(".gallery"),o=document.createElement("div");o.classList.add("gallery-temp");const n=e.map(r=>`<li>
          <a href="${r.largeImageURL}">
            <img src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <div class="info">
            <p><span>Likes</span><br> ${r.likes}</p>
            <p><span>Views</span><br> ${r.views}</p>
            <p><span>Comments</span><br> ${r.comments}</p>
            <p><span>Downloads</span><br> ${r.downloads}</p>
          </div>
        </li>`).join("");o.innerHTML=n;const t=o.querySelectorAll("img"),a=Array.from(t).map(r=>new Promise((f,L)=>{r.onload=f,r.onerror=L}));Promise.all(a).then(()=>{s.insertAdjacentHTML("beforeend",n),v.refresh(),i(),d()}).catch(r=>{console.error("Image loading failed:",r),i(),d()})},M=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},A=()=>{document.querySelector(".search-loader").classList.add("show")},i=()=>{document.querySelector(".search-loader").classList.remove("show")},B=()=>{document.querySelector(".load-more-loader").classList.add("show")},d=()=>{document.querySelector(".load-more-loader").classList.remove("show")},E=()=>{document.querySelector(".load-more").classList.remove("hidden")},u=()=>{document.querySelector(".load-more").classList.add("hidden")},p=document.querySelector(".form"),F=p.querySelector("input[name='search-text']"),I=document.querySelector(".load-more");let l=1,g="";const m=15,y=async(e,s)=>{try{const o=await q(e,s,m);if(!o||!Array.isArray(o.hits))throw new Error("Invalid API response structure");return o}catch{return i(),d(),c.error({title:"",message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB"}),{hits:[],totalHits:0}}};p.addEventListener("submit",async e=>{e.preventDefault();const s=F.value.trim();if(!s){c.warning({title:"Oops!",message:"Please enter a search term!"});return}g=s,l=1,M(),u(),A();const o=await y(s,l);o.hits.length>0?(h(o.hits),Math.ceil(o.totalHits/m)>l&&E()):(u(),c.warning({title:"",message:"Sorry, there are no images matching your search query. Please try again!"}))});I.addEventListener("click",async()=>{l+=1,B();const e=await y(g,l);if(e.hits.length>0){h(e.hits),C();const s=Math.ceil(e.totalHits/m);l>=s&&(u(),c.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#4E75FF",messageColor:"#FAFAFB"}))}});const C=()=>{const e=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
